name: frontend
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  image_picker: ^0.8.9
  fl_chart: ^0.66.0
  provider: ^6.1.1
  english_words: ^4.0.0
  url_launcher: ^6.2.6
  flutter_rating_bar: ^4.0.1
  mailer: ^6.5.0
  # Google Fit API integration
  #fitness: ^1.0.1
  health: ^11.0.2
  permission_handler: ^11.3.1
  #workmanager: ^0.5.2
  #background_fetch: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/hsp.png
    - assets/images/logo.png
    - assets/images/Bewegung.png
    - assets/images/Frisbee.png
    - assets/images/Klingeling.png
    - assets/images/Liegestuhl.png
    - assets/images/Tasche.png